import anthropic
import os, sys
import base64
import re
from dotenv import load_dotenv

## Read ANTHROPIC_API_KEY from .env; an already-exported value wins.
load_dotenv()

MEDIA_TYPES = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg"}

def generate_alt_text(image_path):

  def encode_image(image_path):
      with open(image_path, "rb") as image_file:
          return base64.b64encode(image_file.read()).decode("utf-8")

  ## Set the model name. Credentials come from the environment
  ## (ANTHROPIC_API_KEY, or an `ant auth login` profile).
  MODEL="claude-opus-5"
  client = anthropic.Anthropic()

  media_type = MEDIA_TYPES[os.path.splitext(image_path)[1].lower()]

  message = client.beta.messages.create(
    model=MODEL,
    max_tokens=2000,
    output_config={"effort": "low"},
    betas=["server-side-fallback-2026-07-01"],
    fallbacks="default",
    system=f"You are an alt text generator assistant. You are asked to generate alt text for the image provided. Images are always photos of wombats, both common and hairy-nosed, but there may be other animals or people. All text should be consise, using only lowercase alphanumerical characters with no punctuation. Keep it under 100 characters. don't use the word cozy. its okay to have fun. if the original filename ({image_path}) contains a credit to the photographer (usually 'Photo by <photographer name>…'), add this credit to the end of the alt text, like '<alt text description> (credit: <photographer name>)', e.g. 'Wombat with grass on its head sitting on a log (credit: John Smith)'. Make sure to preserve the photographer's name exactly as it appears in the filename. The photographer name is the text between 'Photo by' and the first ' on <date>' or ' in <location>' or period, so always add the credit if the filename starts with 'Photo by'. If the filename does not contain a credit, do not add one. Reply with the alt text only.",
    messages=[
      {"role": "user", "content": [
        {"type": "image", "source": {
          "type": "base64",
          "media_type": media_type,
          "data": encode_image(image_path)}
        },
        {"type": "text", "text": "Generate alt text for this image:"}
      ]}
    ]
  )

  if message.stop_reason == "refusal":
    raise RuntimeError("model declined to describe this image")

  label = "".join(b.text for b in message.content if b.type == "text").strip()
  print(label)
  return label

if __name__ == "__main__":
  if  len(sys.argv) >= 2 and sys.argv[1] == "-h":
    print ("Usage: python labeler.py")
    print ("")
    print ("Renames files in img_staging to alt text generated by Claude")
    sys.exit(0)
  if not (os.environ.get("ANTHROPIC_API_KEY", "")
          or os.environ.get("ANTHROPIC_AUTH_TOKEN", "")
          or os.path.isdir(os.path.expanduser("~/.config/anthropic"))):
    print ("Error: no Anthropic credentials found (set ANTHROPIC_API_KEY, or run `ant auth login`)")
    sys.exit(0)
  for filename in os.listdir("img_staging"):
    if filename.endswith(".png") or filename.endswith(".jpg"):
      try:
        print ("[old] " + filename)
        # if new filename format, change to match old downloader
        credit_transformed_filename = re.sub(r'^(.*?)-photo-(.*?)$', r'Photo by \1 - \2', filename)
        os.rename("img_staging/" + filename, "img_staging/" + credit_transformed_filename)
        filename = credit_transformed_filename

        label = generate_alt_text("img_staging/" + filename)
        file_extension = os.path.splitext(filename)[1]
        
        os.rename("img_staging/" + filename, "img_staging/" + label + file_extension)
        print ("[new] " + label + file_extension + "\n")
      except Exception as e:
        print ("[error] failure"+ "\n")
        print (str(e) + "\n")
  